services:
  db:
    image: postgres:16.2
    container_name: tcg_shop_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: always

  app:
    build:
      context: .
    container_name: tcg_shop_app
    command: python tcg_shop/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3.13.1-management  # Using the same version as in the command
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # Web management UI
    restart: always